### ISSUE TITLE
no option for disabling AOT

### ISSUE THREAD

**Issue by implicit-invocation** [elysiajs/elysia-cors#20]
[https://github.com/elysiajs/elysia-cors/blob/b0010456ef879cfadc116010f2df65eb31bee1fc/src/index.ts#L171](https://github.com/elysiajs/elysia-cors/blob/b0010456ef879cfadc116010f2df65eb31bee1fc/src/index.ts#L171)

**Comment by SaltyAom** [comment]
`aot: false` is introduced in [Config](https://github.com/elysiajs/elysia-cors/blob/d81de2c157d4f9f7d0b9538a1fc4e0c0934b25ce/src/index.ts#L50C2-L50C15), published under 1.0.4.
