### ISSUE TITLE
DELETE method not allowed by default

### ISSUE THREAD

**Issue by GaspardCulis** [elysiajs/elysia-cors#49]
The [plugin's documentation](https://elysiajs.com/plugins/cors.html#methods) specifies that the default allowed methods is basically the `*` wildcard. However when developing my API with this plugin I encountered CORS issues when trying to call a route using the DELETE method:

```ts
import { Elysia } from "elysia";
import { cors } from "@elysiajs/cors";

import * as gql from "./gql";
import * as media from "./media";

new Elysia()
	.use(cors())
	.group("/api", (app) =>
		app
			.post("/gql", gql.POST)
			.group("/media", (app) =>
				app
					.get("", media.GET)
					.post("", media.POST)
					.delete("", media.DELETE), // This one
			),
	)
	.listen(3000);
```

Fixed it by setting the methods parameter to `*`:

```ts
import { Elysia } from "elysia";
import { cors } from "@elysiajs/cors";

import * as gql from "./gql";
import * as media from "./media";

new Elysia()
	.use(cors({ methods: "*" })) // Here
	.group("/api", (app) =>
		app
			.post("/gql", gql.POST)
			.group("/media", (app) =>
				app
					.get("", media.GET)
					.post("", media.POST)
					.delete("", media.DELETE),
			),
	)
	.listen(3000);
```

Not a huge problem but kinda annoying

**Comment by SaltyAom** [comment]
Should have been fixed with [010f999](https://github.com/elysiajs/elysia-cors/commit/010f99942bd7fad22bb15d48ae91f097da7fcf36), published on 1.0.4.
