### ISSUE TITLE
Version 1.0.3 missing from the npmjs registry

### ISSUE THREAD

**Issue by deanrih** [elysiajs/elysia-cors#51]
I just realized that in the repository there was an update for version 1.0.3 around last month, however when doing package install or update it uses version `1.0.2`, if trying to update it manually with `bun update @elysiajs/cors@^1.0.3` it can't find the version, as well as on the NPMJS page (https://www.npmjs.com/package/@elysiajs/cors) it only mention version `1.0.2` and lists all version up to that version

**Comment by SaltyAom** [comment]
Fixed with latest published on 1.0.4
