### ISSUE TITLE
Upgrading from 1.0.2 to 1.0.4 causes CORS errors even if I `cors({ origin: true, credentials: true })`

### ISSUE THREAD

**Issue by Blankeos** [elysiajs/elysia-cors#53]
As the title says. Not sure what's going on...

Code: (no changes)
<img width="273" alt="image" src="https://github.com/elysiajs/elysia-cors/assets/38070918/0b610d26-775a-40ab-bcc0-e3d2cc7adcbf">

I also tried `cors({ origin: true, credentials: true })`

- 1.0.2
<img width="477" alt="image" src="https://github.com/elysiajs/elysia-cors/assets/38070918/3704a078-8931-42c0-9c67-9523ce5f007b">

- 1.0.4
<img width="487" alt="image" src="https://github.com/elysiajs/elysia-cors/assets/38070918/9bcfaebc-910e-4702-9734-368098f90a78">

**Comment by lyorb** [comment]
Same problem, need to downgrade to 1.0.2 @SaltyAom

**Comment by SaltyAom** [comment]
Hi, can you please also attach an error message.
You can find one in `console` tab, thanks

**Comment by Blankeos** [comment]
Hi @SaltyAom, no logs on the console surprisingly. Checked both in the browser and the backend. Don't mind the embed errors:

https://github.com/user-attachments/assets/2ec18534-0a8c-47a2-90e1-14a7597580e8

**Comment by Blankeos** [comment]
I'm trying to make a repro right now. It's weird. It actually works on a minimal example, but for my project it doesn't. Let me try to investigate some more.

Might be related to https, TLS, or whatever (i'm running mine on HTTPs for browser Geo apis to work). No idea. I'll try experimenting.

**Comment by SaltyAom** [comment]
Should be fixed by [a2a179a](https://github.com/elysiajs/elysia-cors/commit/a2a179ac4ee9eba5fdb167c1422403c28371f382), published under 1.0.5

**Comment by Blankeos** [comment]
Works great. Thanks @SaltyAom !
